apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: agentic-chatbot-sep21-2
  janus-idp.io/tekton: agentic-chatbot-sep21-2
  backstage.io/kubernetes-id: agentic-chatbot-sep21-2
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: agentic-chatbot-sep21-2
resources:
  - application-dev.yaml