apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: agentic-chatbot-sep21-2-gitops-repository
spec:
  url: https://github.com/rhdh-JslYoon-org/agentic-chatbot-sep21-2-gitops
