apiVersion: v1
kind: ConfigMap
metadata:
  name: agentic-chatbot-sep21-2-model-config
data:
  MODEL_ENDPOINT: "http://agentic-chatbot-sep21-2-model-server:8001"
  MODEL_NAME: "ibm-granite/granite-3.3-8b-instruct"
