apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: agentic-chatbot-sep21-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rh-ee-lyoon-dh/agentic-chatbot-sep21-2:9346b669e9dfcc4aab033c5e75bc962d2f993fe3@sha256:6eef1b6f314a82f4289fd106602ee60740e49f670af65f6be257414db891a881 # use pre-built to bootstrap
          name: app-inference
